### ISSUE TITLE
Does not install (npm install fails)

### ISSUE THREAD

**Issue by pkellner** [oktadeveloper/okta-node-express-15-minute-auth-example#5]
code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
npm ERR! 404 
npm ERR! 404  'event-stream@3.3.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'okta-node-express-15-minute-auth-example'
npm ERR! 404

**Comment by mraible** [comment]
@pkellner Our SDKs automatically refresh tokens when they expire. In fact, you have to turn this feature off if you don't want this functionality.

**Comment by pkellner** [comment]
That works? even in the Passport strategy flow?  How could it update session where the bearer token Is stored.  I get with your native implementation how it could work.

**Comment by mraible** [comment]
I haven't used Passport, so I'm not sure. [OAuth2 Refresh Tokens in Passport.js](http://abashev.com/articles/oauth2-refresh-tokens-in-passport-js/) seems to indicate you have to write a bit of code to auto-refresh tokens.
